version: "3"
services:
       mongotrailserver:
           container_name: mongotrailserver
           image: v2/mtblocation
           restart: always
           build: .
           ports:
             - "3007:3007"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27018:27017'